### ISSUE TITLE
Add support for /api/v1/members

### ISSUE THREAD

**Issue by lol768** [mbg/uow-apis#6]

**Comment by mbg** [comment]
Pending on documentation for this API endpoint

**Comment by lol768** [comment]
It will be here https://warwick.ac.uk/services/its/servicessupport/web/tabula/api/member/search-for-members

**Comment by mbg** [comment]
That documentation is pretty poor. Guess I am going to have to `curl` the endpoint to figure out what format the response it sends back is in?

**Comment by matmannion** [comment]
The documentation that's there is just a stub, but I'll pick up fleshing it out today.

**Comment by mbg** [comment]
Ah I see, thank you!

**Comment by lol768** [comment]
Emphasis on _will_ :P

**Comment by matmannion** [comment]
I've fleshed out the documentation now, although the endpoint itself won't be live until 2019.8.3 is released tomorrow morning

**Comment by mbg** [comment]
Thanks for the update!

**Comment by mbg** [comment]
I have implemented this now in a09d0e5352c4872d429c7e735c734e86d211f2eb and was able to test it with the `tabula-test` instance. One thing I noticed though that particularly for listing the members of a module, it would be useful to specify the academic year (e.g. searching for "cs141" seems to return nothing because there are no students registered for it yet this year)

**Comment by mbg** [comment]
Merged this now since it seems to work with the live instance as well.
